import { Slot } from '@radix-ui/react-slot'
import { type VariantProps, cva } from 'class-variance-authority'
import type { ComponentPropsWithoutRef } from 'react'
import { cn } from '../utils/cn'

/**
 * Button — the shadcn/ui primitive, themed on KroTokens.
 *
 * Every value below is a token utility (`bg-kro-…`, `rounded-kro-…`,
 * `shadow-kro-…`) generated by the `@theme inline` block in `globals.css`, so
 * a re-tune happens in `tokens.css` and lands here without an edit.
 *
 * THE DISABLED FADE IS APPLIED EXACTLY ONCE.
 * `--kro-opacity-disabled` (0.62) appears in the base classes and nowhere
 * else. A wrapper that dims its subtree while this also dims itself multiplies
 * the two to ~0.38 and drops the control below the 3:1 floor for UI elements —
 * KroApple has the same note at the token's declaration, and
 * `button.test.tsx` asserts the class appears once.
 *
 * The 44px minimum height is the iOS touch floor; the `sm` size drops to the
 * 28px pointer target for desktop-only chrome, per the epic's idiom rules.
 */
const buttonVariants = cva(
  cn(
    'inline-flex shrink-0 items-center justify-center gap-kro-small',
    'cursor-default whitespace-nowrap font-medium',
    'kro-motion-quick transition-[color,background-color,box-shadow,transform]',
    'outline-none focus-visible:shadow-[var(--kro-ring)]',
    'active:scale-[0.97]',
    'disabled:pointer-events-none disabled:opacity-[var(--kro-opacity-disabled)]',
    "[&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-5",
  ),
  {
    variants: {
      variant: {
        /** The one primary action on a surface. Reads on the live accent. */
        primary:
          'bg-kro-accent text-kro-on-accent shadow-kro-subtle hover:brightness-110',
        /** Everything alongside it. */
        secondary:
          'bg-kro-back-inner text-kro-fore shadow-kro-subtle hover:bg-kro-back-next',
        /** Low-emphasis, inline with content. */
        ghost: 'text-kro-fore hover:bg-kro-back-inner',
        /** Destructive. Paired with a word — never colour alone (epic AC 9). */
        destructive:
          'bg-kro-banner-danger text-white shadow-kro-subtle hover:brightness-110',
        /**
         * The KroGlass control. The material lives in `glass.css`, including
         * the Safari fix and every fallback, so this variant only asks for it.
         */
        glass:
          'kro-glass kro-glass--control kro-glass--interactive px-kro-medium',
      },
      size: {
        /** Desktop-only chrome: the 28px pointer target. */
        sm: 'h-7 rounded-kro-small px-kro-small text-sm',
        /** The default. The 44px touch floor. */
        md: 'h-11 rounded-kro-field px-kro-medium text-base',
        lg: 'h-12 rounded-kro-field px-kro-large text-base',
        /** Icon-only, still a full touch target. */
        icon: 'size-11 rounded-kro-field',
        /** Icon-only on desktop. */
        'icon-sm': 'size-7 rounded-kro-small',
        pill: 'h-11 rounded-kro-pill px-kro-large text-base',
      },
    },
    defaultVariants: { variant: 'secondary', size: 'md' },
  },
)

export interface ButtonProps
  extends ComponentPropsWithoutRef<'button'>,
    VariantProps<typeof buttonVariants> {
  /**
   * Render the child element instead of a `button`, keeping every class and
   * handler. The escape hatch for a link that must look like a button —
   * without nesting an anchor inside a button, which is invalid.
   */
  readonly asChild?: boolean
}

export function Button({
  className,
  variant,
  size,
  asChild = false,
  type,
  ...rest
}: ButtonProps) {
  const Component = asChild ? Slot : 'button'

  return (
    <Component
      data-slot="button"
      // A button inside a form defaults to `submit` in HTML, which is how a
      // "Cancel" control ends up submitting the form it sits in.
      type={asChild ? undefined : (type ?? 'button')}
      className={cn(buttonVariants({ variant, size }), className)}
      {...rest}
    />
  )
}

export { buttonVariants }
