/**
 * `@kro/app/design` HIG catalog — Apple's component titles, realised in
 * KroTokens and KroGlass.
 *
 * Visual language is Kro's. Use cases, layouts and purposes follow
 * https://developer.apple.com/design/human-interface-guidelines/components
 *
 * `RC-14`: nothing here imports react-redux or a slice. State arrives as props.
 */

export {
  HIG_CATALOG,
  HIG_CATEGORIES,
  HIG_COMPONENTS_INDEX,
  type HigAvailability,
  type HigCatalogEntry,
  type HigCategory,
  higEntriesByCategory,
  higEntryNamed,
  higUrl,
} from './catalog'
export {
  HIG_STAGE_BACKDROP,
  HigBothSchemes,
  HigDensities,
  HigRow,
  HigStage,
  type HigStageProps,
} from './higStoryStage'

export {
  PopupButton,
  PopupChoiceRow,
  PullDownButton,
  PullDownChoiceRow,
  pullDownItemIsDestructive,
  selectedPopupLabel,
  type PopupButtonOption,
  type PopupButtonProps,
  type PullDownButtonItem,
  type PullDownButtonProps,
  type PullDownTone,
} from './actions'
export {
  Chart,
  ImageView,
  TextView,
  WebView,
  chartSpokenName,
  restrictedSandbox,
  type ChartProps,
  type ChartTone,
  type ChartValue,
  type ImageViewAspect,
  type ImageViewProps,
  type ImageViewShape,
  type TextViewProps,
  type WebViewProps,
} from './content'
export {
  Collection,
  CollectionItem,
  ColumnView,
  Disclosure,
  GroupedBox,
  Label,
  List,
  ListRow,
  ListSection,
  Lockup,
  OutlineView,
  ScrollView,
  Separator,
  SplitView,
  type CollectionItemProps,
  type CollectionProps,
  type ColumnViewColumn,
  type ColumnViewItem,
  type ColumnViewProps,
  type DisclosureProps,
  type GroupedBoxProps,
  type LabelAs,
  type LabelProps,
  type LabelSize,
  type LabelTone,
  type ListProps,
  type ListRowProps,
  type ListSectionProps,
  type LockupProps,
  type OutlineViewItem,
  type OutlineViewProps,
  type ScrollViewAxis,
  type ScrollViewProps,
  type SeparatorProps,
  type SplitViewProps,
} from './layout'
export {
  NavigationBar,
  PathControl,
  SearchField,
  Sidebar,
  TabBar,
  Toolbar,
  type NavigationBarProps,
  type PathControlItem,
  type PathControlProps,
  type SearchFieldProps,
  type SidebarAppearance,
  type SidebarChild,
  type SidebarItem,
  type SidebarProps,
  type TabBarItem,
  type TabBarProps,
  type ToolbarProps,
} from './navigation'
export {
  ActionSheet,
  ActionSheetAction,
  ActionSheetContent,
  ActionSheetTitle,
  ActionSheetTrigger,
  Alert,
  AlertActions,
  AlertContent,
  AlertDescription,
  AlertTitle,
  AlertTrigger,
  Panel,
  type ActionSheetActionProps,
  type ActionSheetTone,
  type PanelProps,
} from './presentation'
export {
  Checkbox,
  ColorWell,
  ComboBox,
  DigitEntry,
  Picker,
  Radio,
  RadioGroup,
  Slider,
  Stepper,
  Toggle,
  type CheckboxProps,
  type ColorWellProps,
  type ComboBoxProps,
  type DigitEntryProps,
  type PickerOption,
  type PickerProps,
  type RadioGroupProps,
  type RadioProps,
  type SliderProps,
  type StepperProps,
  type ToggleProps,
} from './selection'
export {
  Gauge,
  ProgressIndicator,
  RATING_MAX,
  RatingIndicator,
  clampUnitInterval,
  gaugeAccessibleName,
  type GaugeProps,
  type ProgressIndicatorAppearance,
  type ProgressIndicatorKind,
  type ProgressIndicatorLabelPosition,
  type ProgressIndicatorProps,
  type ProgressIndicatorSize,
  type RatingIndicatorProps,
} from './status'
