/**
 * The chrome tier's springs, sampled from KroApple's own.
 *
 * WHY THIS FILE EXISTS. `system/motion` ports the two springs KroTokens names
 * (`quickSpring`, `standardSpring`). The bottom chrome does not use either:
 * `ActiveToastModifier` animates on `.spring(response: 0.4, dampingFraction:
 * 0.8)`, `LiquidGlassFABMenu` on `0.32/0.78` opening and `0.28/0.82` closing,
 * `ActivityRings` on `0.5/0.8`. Those are canon's numbers for these surfaces,
 * so rounding them to the nearest token would be a different animation wearing
 * the token's name.
 *
 * HOW IT STAYS HONEST. Nothing here is hand-typed. Every curve is generated by
 * the SAME `springDisplacement` the design system samples its own curves from,
 * so a chrome spring and a token spring are the same maths — and
 * `chromeMotion.test.ts` regenerates them and compares, which is why a
 * hand-edited stop fails the suite rather than shipping.
 *
 * TWO SWIFTUI SPRING SPELLINGS, ONE MODEL. KroTokens uses
 * `spring(duration:bounce:)`; the chrome uses `spring(response:dampingFraction:)`.
 * They parameterise the same damped oscillator: `duration` and `response` are
 * both the undamped period (omega = 2pi / p), and `bounce = 1 - dampingFraction`.
 * `springDisplacement` therefore answers for both — `fromResponse` below is the
 * whole translation.
 *
 * REDUCED MOTION is not handled here and does not need to be. Every curve below
 * is consumed as a `transition-timing-function` with a `transition-duration`,
 * and `motion.css`'s blanket rule collapses every transition duration to
 * 0.01ms under `prefers-reduced-motion`. A spring with no time to run is a
 * jump, which is the intent.
 */

import { springDisplacement } from '../../system/motion/motion'

/** A SwiftUI `spring(response:dampingFraction:)`, as written at the call site. */
export interface CanonSpring {
  readonly response: number
  readonly dampingFraction: number
}

/**
 * The springs this kit ports, each labelled with the canon call site so a
 * reviewer can diff a number against a file rather than against memory.
 */
export const CHROME_SPRINGS = {
  /** `ActiveToastModifier` — `.animation(.spring(response: 0.4, dampingFraction: 0.8), value: toast?.id)`. */
  toast: { response: 0.4, dampingFraction: 0.8 },
  /** `LiquidGlassFABMenu.mainButton` — the expand/collapse toggle. */
  menuExpand: { response: 0.32, dampingFraction: 0.78 },
  /** `LiquidGlassFABMenu.triggerAndCollapse` — the snap shut after a choice. */
  menuCollapse: { response: 0.28, dampingFraction: 0.82 },
  /** `ActivityRings.body` — `.animation(… .spring(response: 0.5, dampingFraction: 0.8), value: rings)`. */
  rings: { response: 0.5, dampingFraction: 0.8 },
} as const satisfies Record<string, CanonSpring>

export type ChromeSpringName = keyof typeof CHROME_SPRINGS

/**
 * `ActiveToastModifier` — `.animation(.easeInOut(duration: 0.22), value: verticalLift)`.
 *
 * A plain ease, not a spring: the lift is a layout correction when the Session
 * Pill appears, and canon deliberately does not let it overshoot into the pill
 * it just moved to clear.
 */
export const TOAST_LIFT = {
  ms: 220,
  easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
} as const

/** The `{ duration, bounce }` pair `springDisplacement` takes, from canon's spelling. */
function fromResponse({ response, dampingFraction }: CanonSpring): {
  duration: number
  bounce: number
} {
  return { duration: response, bounce: 1 - dampingFraction }
}

/**
 * Residual amplitude at which a spring is called settled.
 *
 * 0.2% — the same bar `motion.css` states for the token springs, so a chrome
 * curve and a token curve are cut off at the same point rather than one
 * looking longer than the other for no reason.
 */
export const SETTLE_RESIDUAL = 0.002

/** Points sampled across the settle time. Matches `motion.css`'s 25. */
export const SAMPLE_COUNT = 25

/**
 * How long the spring takes to fall under `SETTLE_RESIDUAL`, in milliseconds.
 *
 * Closed form rather than a search: the envelope is `e^(-zeta*omega*t)`, so the
 * crossing is `-ln(residual) / (zeta * omega)`. This is the number that must be
 * used as the transition's DURATION — pairing a spring curve with a shorter
 * duration cuts the overshoot off mid-flight, which is the failure
 * `system/motion/motion.css` warns about.
 */
export function settleMs(spring: CanonSpring): number {
  const omega = (2 * Math.PI) / spring.response
  const zeta = spring.dampingFraction
  // Ceil, not round. Rounding down lands the transition a fraction of a
  // millisecond BEFORE the crossing, which leaves the residual just above the
  // bar this function exists to guarantee.
  return Math.ceil((-Math.log(SETTLE_RESIDUAL) / (zeta * omega)) * 1000)
}

/**
 * The spring as a CSS `linear()` easing, sampled over its settle time.
 *
 * Stops above 1 near the end are the overshoot; they are the point of a spring,
 * not a rounding artefact.
 */
export function springEasing(spring: CanonSpring): string {
  const params = fromResponse(spring)
  const settleSeconds = settleMs(spring) / 1000
  const stops: string[] = []
  for (let index = 0; index < SAMPLE_COUNT; index += 1) {
    const t = (index / (SAMPLE_COUNT - 1)) * settleSeconds
    const value = index === SAMPLE_COUNT - 1 ? 1 : springDisplacement(t, params)
    stops.push(Number(value.toFixed(4)).toString())
  }
  return `linear(${stops.join(', ')})`
}

/** A ready-to-spread `transition` pair for one of the named chrome springs. */
export function springTransition(
  name: ChromeSpringName,
  properties: readonly string[],
): { transitionProperty: string; transitionDuration: string; transitionTimingFunction: string } {
  const spring = CHROME_SPRINGS[name]
  return {
    transitionProperty: properties.join(', '),
    transitionDuration: `${settleMs(spring)}ms`,
    transitionTimingFunction: springEasing(spring),
  }
}
