/**
 * `@kro/app/design` Fluent 2 catalog — Fluent's component titles, realised
 * in KroTokens and KroGlass.
 *
 * Visual language is Kro's. Use cases, variants and sizes follow
 * https://fluent2.microsoft.design/components/web/react
 *
 * Exact-name collisions with a live HIG/Kro export are restaged, not
 * re-exported. `RC-14`: nothing here imports react-redux or a slice.
 */

export {
  FLUENT_CATALOG,
  FLUENT_CATEGORIES,
  FLUENT_COMPONENTS_INDEX,
  type FluentAvailability,
  type FluentCatalogEntry,
  type FluentCategory,
  type FluentConflict,
  type FluentConflictKind,
  fluentConflicts,
  fluentEntriesByCategory,
  fluentEntryNamed,
  fluentUrl,
} from './catalog'
export {
  FLUENT_STAGE_BACKDROP,
  FluentBothSchemes,
  FluentDensities,
  FluentRow,
  FluentStage,
  type FluentStageProps,
} from './fluentStoryStage'
export {
  FLUENT_CONTROL_SIZES,
  buttonSizeForFluentSize,
  densityForFluentSize,
  fluentSizeForDensity,
  type FluentControlSize,
} from './sizes'

export {
  FLUENT_BUTTON_APPEARANCES,
  CompoundButton,
  Link,
  MenuButton,
  MenuButtonChoiceRow,
  SplitButton,
  ToggleButton,
  menuButtonItemIsDestructive,
  type CompoundButtonProps,
  type FluentButtonAppearance,
  type LinkAppearance,
  type LinkProps,
  type MenuButtonItem,
  type MenuButtonProps,
  type MenuButtonTone,
  type SplitButtonProps,
  type ToggleButtonProps,
} from './actions'
export {
  AVATAR_SIZES,
  Avatar,
  AvatarGroup,
  PRESENCE_KINDS,
  Persona,
  PresenceBadge,
  TEXT_SIZES,
  Text,
  avatarSizePx,
  initialsFromName,
  presenceLabel,
  type AvatarColor,
  type AvatarGroupLayout,
  type AvatarGroupProps,
  type AvatarProps,
  type AvatarShape,
  type AvatarSize,
  type PersonaProps,
  type PersonaSize,
  type PersonaTextAlignment,
  type PresenceBadgeProps,
  type PresenceKind,
  type TextAs,
  type TextProps,
  type TextSize,
  type TextTone,
  type TextWeight,
} from './content'
export {
  Field,
  InfoLabel,
  Select,
  SpinButton,
  TagPicker,
  type FieldOrientation,
  type FieldProps,
  type FieldValidationState,
  type InfoLabelProps,
  type SelectAppearance,
  type SelectOption,
  type SelectProps,
  type SpinButtonProps,
  type TagPickerProps,
} from './forms'
export {
  Accordion,
  Breadcrumb,
  Nav,
  type AccordionItem,
  type AccordionProps,
  type BreadcrumbItem,
  type BreadcrumbProps,
  type NavAppearance,
  type NavChild,
  type NavItem,
  type NavProps,
  type NavSize,
} from './navigation'
export {
  Card,
  CardFooter,
  CardHeader,
  CardPreview,
  Carousel,
  Tooltip,
  type CardAppearance,
  type CardFooterProps,
  type CardHeaderProps,
  type CardOrientation,
  type CardPreviewProps,
  type CardProps,
  type CarouselProps,
  type CarouselSlide,
  type TooltipProps,
  type TooltipRelationship,
} from './surfaces'
export {
  BADGE_APPEARANCES,
  BADGE_COLORS,
  Badge,
  CounterBadge,
  MessageBar,
  SPINNER_PX,
  SPINNER_SIZES,
  Skeleton,
  SkeletonItem,
  Spinner,
  TAG_APPEARANCES,
  TAG_SIZES,
  Tag,
  TagGroup,
  type BadgeAppearance,
  type BadgeColor,
  type BadgeProps,
  type BadgeShape,
  type BadgeSize,
  type CounterBadgeProps,
  type MessageBarAction,
  type MessageBarIntent,
  type MessageBarLayout,
  type MessageBarProps,
  type SkeletonAnimation,
  type SkeletonAppearance,
  type SkeletonItemProps,
  type SkeletonProps,
  type SpinnerAppearance,
  type SpinnerLabelPosition,
  type SpinnerProps,
  type SpinnerSize,
  type TagAppearance,
  type TagGroupProps,
  type TagProps,
  type TagShape,
  type TagSize,
} from './status'
